# This file should be symlinked from ~/.gvimrc

" colorscheme elflord
" Remove icons:
aunmenu ToolBar.Make
aunmenu ToolBar.RunCtags
" Remove toolbar by default
set guioptions-=T
set guioptions=mrb

" set guifont=NotoMono\ Nerd\ Font\ Mono:h11
set guifont=Noto\ Mono\ for\ Powerline\ 11

if &encoding ==# 'latin1'
  set encoding=utf-8
endif

" Toggle toolbar visibility
command! ToggleToolbar :if &go=~#'T'<Bar>set go-=T<Bar>else<Bar>set go+=T<Bar>endif<CR>

augroup gvimrc
  autocmd!
  " Disable annoying sound bell.
  autocmd GUIEnter * set visualbell t_vb=

  set lines=45
augroup END
