#!/bin/sh
#
# AUTHOR: Henri K
#
# Date
#
# DESC: Elvi to search <name>
# elvis: <lyh>		-- Search <name(url)>
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "url"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "url{escaped_args}"
fi
