# Should be similar to default starship.toml but shows current shell.

# Configuration | Starship
# https://starship.rs/config/

# $env_var\
# $custom\

add_newline = true

# Modules the prompt has

# NOTE: Don't add sudo -module. It spams journalctl with messages after every command.

format = """
$shell\
$username\
$hostname\
$shlvl\
$php\
$python\
$ruby\
$nodejs\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$memory_usage\
$env_var\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$container\
$character"""

# Module options

[shell]
disabled = false

[status]
disabled = false

[character]
vicmd_symbol = "[N](bold blue) ❯"
